# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html
* Уэс Маккини. Python и анализ данных

## Задачи для совместного разбора

In [ ]:
import numpy as np
lst=[1,2,3,4,6,7,9]
lst
[i**2 for i in lst]


In [ ]:
arr= np.array(lst)
arr**2

In [14]:
mask = arr < 4
mask

array([ True,  True,  True, False, False, False, False])

In [15]:
arr[mask]

array([1, 2, 3])

In [17]:
arr= np.arange(20).reshape(5,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [19]:
arr[:3,:]

array([[0, 1],
       [4, 5],
       [8, 9]])

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [102]:
import pandas as pd

file=np.loadtxt("C:/Users/194166/Downloads/data/minutes_n_ingredients.csv",dtype='int32', skiprows=1, delimiter="," )
print (file[:5])




[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [107]:
a=np.max(file,axis=0 )[:2]
print (a, "max")
a=(np.min(file,axis=0))[:2]
print (a, "min")
a=np.average(file,axis=0)[:2] #mean
print (a,"average")
a=np.median(file,axis=0)[:2]
print (a,"median")

[    537671 2147483647] max
[38  0] min
[222064.32391  21601.00169] average
[2.071935e+05 4.000000e+01] median


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [96]:
kvant=np.quantile(file,0.75)
print (kvant)
file[file>kvant]=kvant
print (file[:10])


100064.25
[[100064     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [100064     60     14]
 [100064     40      7]
 [ 33941     18      9]
 [100064     15      5]
 [100064      7      9]
 [ 74205     20      7]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [97]:
file[file==0]=1
print (file[:10])

[[100064     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [100064     60     14]
 [100064     40      7]
 [ 33941     18      9]
 [100064     15      5]
 [100064      7      9]
 [ 74205     20      7]]


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [99]:
np.unique(file, return_counts=True)

(array([     1,      2,      3, ..., 100060, 100062, 100064]),
 array([  729,  1738,  3358, ...,     1,     1, 75001], dtype=int64))

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

13. Выведите процент "простых" рецептов в датасете

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.