# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html
* Уэс Маккини. Python и анализ данных

## Задачи для совместного разбора

In [54]:
import numpy as np
lst=[1,2,3,4,6,7,9]
lst
[i**2 for i in lst]


[1, 4, 9, 16, 36, 49, 81]

In [ ]:
arr= np.array(lst)
arr**2

array([ 1,  4,  9, 16, 36, 49, 81])

In [ ]:
mask = arr < 4
mask

array([ True,  True,  True, False, False, False, False])

In [ ]:
arr[mask]

array([1, 2, 3])

In [ ]:
arr= np.arange(20).reshape(5,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
arr[:3,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [55]:
import pandas as pd

file=np.loadtxt("/content/minutes_n_ingredients.csv",dtype='int32', skiprows=1, delimiter="," )
print (file[:5])




[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [ ]:
maax=np.max(file,axis=0 )[1:]
print (maax, "max")
miin=(np.min(file,axis=0))[1:]
print (miin, "min")
avvr=np.average(file,axis=0)[1:] #mean
print (avvr,"average")
medd=np.median(file,axis=0)[1:]
print (medd,"median")

[2147483647         39] max
[0 1] min
[2.16010017e+04 9.05528000e+00] average
[40.  9.] median


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [69]:
copy = file #[:,1:3]
#print (copy[:,1:2])
kvant=np.quantile(copy[:,1:2],0.75)
#print (copy[:,0:1])
print (kvant," Квантиль\n")
print (copy[copy<=kvant])



# if (maax[1]>9):
#   maax[1]=9
# print (maax)

# if (miin[1]>9):
#   miin[1]=9
# print (miin)
# if (avvr[1]>9):
#   avvr[1]=9.0
# print (avvr)
# if (medd[1]>9):
#   medd[1]=9.0
# print (medd)

65.0  Квантиль

[60 16 25 ...  5  4 14]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [87]:
file=np.loadtxt("/content/minutes_n_ingredients.csv",dtype='int32', skiprows=1, delimiter="," )

temp=file[:,1:2]
count = np.count_nonzero(temp == 0)
print (count, "кол-во 0 в таблице")
temp[temp==0]=1
term=file[:,2:]
file=file[:,:-2]
print (temp)
file=np.append(file, temp, axis=1)
file=np.append(file, term, axis=1)
print (file)
#print (file[cor])


479 кол-во 0 в таблице
[[ 60]
 [ 25]
 [ 10]
 ...
 [ 65]
 [  5]
 [140]]
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993    140     14]]


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [88]:
(uniq, freq)=np.unique(file, return_counts=True)
print (uniq.size , "уникальные значения")

100544 уникальные значения


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [89]:
dictat=dict(zip(uniq, freq))
print (dictat)

{1: 729, 2: 1738, 3: 3358, 4: 5783, 5: 11997, 6: 9723, 7: 11035, 8: 11327, 9: 10700, 10: 14469, 11: 8518, 12: 7062, 13: 5392, 14: 3808, 15: 7859, 16: 2036, 17: 1725, 18: 1222, 19: 694, 20: 6777, 21: 419, 22: 756, 23: 511, 24: 200, 25: 5691, 26: 207, 27: 477, 28: 335, 29: 88, 30: 7970, 31: 117, 32: 351, 33: 241, 34: 80, 35: 5375, 36: 75, 37: 185, 38: 177, 39: 49, 40: 6093, 41: 50, 42: 179, 43: 80, 44: 44, 45: 4957, 46: 55, 47: 74, 48: 102, 49: 20, 50: 4266, 51: 30, 52: 60, 53: 65, 54: 18, 55: 3040, 56: 22, 57: 65, 58: 31, 59: 13, 60: 4464, 61: 25, 62: 41, 63: 39, 64: 24, 65: 2355, 66: 16, 67: 36, 68: 32, 69: 4, 70: 2648, 71: 7, 72: 51, 73: 12, 74: 15, 75: 2711, 76: 11, 77: 7, 78: 19, 79: 11, 80: 1886, 81: 11, 82: 15, 83: 10, 84: 15, 85: 760, 86: 6, 87: 14, 88: 11, 89: 9, 90: 1746, 91: 6, 92: 6, 93: 8, 94: 7, 95: 523, 96: 11, 97: 11, 98: 8, 99: 9, 100: 605, 101: 4, 102: 13, 103: 1, 104: 5, 105: 716, 106: 1, 107: 7, 108: 3, 109: 5, 110: 446, 111: 3, 112: 8, 114: 3, 115: 169, 116: 1, 117: 

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [30]:
copy = np.copy(file)
#print (copy[:20])
#print ([copy[:, 2] >5]) copy[:,[2] ]
cop = ([copy[:, 2] <=5])
print (copy[cop])

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [36]:
#print (uniq)
import math
file=np.loadtxt("/content/minutes_n_ingredients.csv",dtype='int32', skiprows=1, delimiter="," )
maxx=0
for i in file:
  if (i[2]/i[1]>maxx and  not(math.isinf(i[2]/i[1]))):
    maxx=i[2]/i[1]
  print (i[0],i[2]/i[1])
print ("the biggest num is ...", maxx)

127244 0.26666666666666666
23891 0.28
94746 0.6
67660 1.2
157911 0.23333333333333334
152828 0.175
33941 0.5
446597 0.3333333333333333
366174 1.2857142857142858
74205 0.35
504666 0.3076923076923077
81006 0.5833333333333334
280968 0.12941176470588237
204134 0.6
18593 0.2
25623 0.6666666666666666
65559 0.5833333333333334
99836 0.03888888888888889
87775 0.1625
425704 0.3
101799 0.8
106325 0.15714285714285714
99283 0.01904761904761905
179504 0.07333333333333333
276123 0.11666666666666667
498382 0.21176470588235294
197140 0.15
484223 0.2222222222222222
385472 0.1
63150 0.016
378114 0.55
318295 0.05384615384615385
259784 0.1
308301 0.09166666666666666
422795 0.23333333333333334
104773 0.07333333333333333
114103 0.01981981981981982
496430 0.25
160325 0.15555555555555556
328135 0.4
69317 0.8
70453 0.16
52233 0.32
63368 0.14545454545454545
66842 2.0
337928 0.07272727272727272
95046 0.4
140245 1.0
299022 0.24
292204 0.4
141000 0.45714285714285713
39771 0.5625
104103 0.5333333333333333
402696 0.3


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in int_scalars
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in int_scalars
  


Выходные данные были обрезаны до нескольких последних строк (5000).
455166 0.2
295709 0.09333333333333334
317320 0.23333333333333334
174617 0.12
486490 0.17777777777777778
64313 0.024
145344 0.8
295861 0.28
156054 0.048
198594 0.14444444444444443
339251 0.2571428571428571
158813 0.08333333333333333
35393 0.34782608695652173
8332 0.2571428571428571
288515 0.12727272727272726
213143 0.11428571428571428
248276 0.1125
36220 0.6
155376 0.12857142857142856
221974 0.6666666666666666
289651 0.7
435254 0.12121212121212122
226223 0.2222222222222222
126319 0.325
158348 0.03793103448275862
316092 0.14285714285714285
59118 0.36
12104 0.3333333333333333
246285 0.12
230140 0.4
93117 0.2222222222222222
53091 0.18461538461538463
154660 0.09230769230769231
259120 0.225
48251 0.10588235294117647
407415 0.34285714285714286
322853 0.24444444444444444
110257 0.0013864818024263432
56013 0.1
151201 1.5
374358 0.5333333333333333
314128 0.4857142857142857
259088 0.15
217420 0.4666666666666667
300451 0.2
49652 0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [51]:
#print (file[file[:,1].argsort()][:100])
temp = file[file[:,1].argsort()][:100]
temp=temp[:,2:3]
#print (temp)
temp=np.average(temp,axis=0) #mean
print (temp,"average")

[9.79] average


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [52]:
random_row=file.shape[0]
random_rows=np.random.choice(random_row,size=10)
print (file[random_rows,:])


[[169648      5      2]
 [458298     20      5]
 [142954     50     10]
 [333156     55      6]
 [347831     20      6]
 [ 47748    105     16]
 [ 95030     15      6]
 [108473     22      7]
 [421220     70      4]
 [121445      5      3]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [53]:
percentages = dict(zip(uniq, freq * 100 / len(file)))
#max(percentages, key=percentages.get)

max_value = min(percentages.values())  # maximum value
max_keys = [k for k, v in percentages.items() if v == max_value] # getting all keys containing the `maximum`

print(max_value,"проц соотношение")#, max_keys)

0.001 проц соотношение


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [ ]:
copy = np.copy(file)
a,b=file.shape
z=np.zeros((a,1), dtype=int)
copy=np.append(copy,z,axis=1)
for i in copy:
  if (i[1]<20 and i[2]<5):
    i[3]=1

print (copy)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [ ]:

copy=copy[copy[:, 3].argsort()]
copy=copy[:,3]
unique, counts = np.unique(copy, return_counts=True)
print (unique,counts)
percentages = (copy/copy.sum(axis=0)*100)
print (percentages[-1],"\nanother method")
# maxx=counts[0]+counts[1]
# print (maxx)



[0 1] [94907  5093]
0.0196347928529354 
another method


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [ ]:
copy=np.copy(file)
row, col = copy.shape
print (row)

final_array = np.zeros((3,row,3))
print (final_array)
count=0
for i in copy:
  if (i[1]<10):
    final_array[][][]=1
    final_array[:,:,1]=i[1]
    final_array[:,:,2]=i[2]
  
  elif (i[1]>=10 and i[1]<20):
    final_array[:,:,0]=2
    final_array[:,:,1]=i[1]
    final_array[:,:,2]=i[2]
  
  elif (i[1]>=20):
    final_array[:,:,0]=3
    final_array[:,:,1]=i[1]
    final_array[:,:,2]=i[2]
  
  count+=1

print (final_array)

100000
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


IndexError: ignored